config:
  validation: true
  warningsAsErrors: false

complexity:
  active: true
  LongMethod:
    active: true
    allowedLines: 80
  LongParameterList:
    active: true
    allowedFunctionParameters: 8
    allowedConstructorParameters: 8
    ignoreDefaultParameters: true
    ignoreAnnotatedParameter: ['Composable']
  CyclomaticComplexMethod:
    active: true
    allowedComplexity: 20
  TooManyFunctions:
    active: false

style:
  active: true
  MagicNumber:
    active: true
    ignoreAnnotated: ['Composable', 'Preview']
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  ReturnCount:
    active: true
    max: 4
  UnusedPrivateProperty:
    active: true
  UnusedPrivateFunction:
    active: true
  UnusedPrivateClass:
    active: true
  ForbiddenComment:
    active: false

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  SuspendFunWithFlowReturnType:
    active: true
